name: "my-docker-project"

services:
  app:
    image: my-docker-image
    container_name: my-docker-container
    ports:
      - "8001:8000"
    environment:
      ENVIRONMENT: ${ENVIRONMENT}
      RENDER_EXTERNAL_HOSTNAME: ${RENDER_EXTERNAL_HOSTNAME}
      SECRET_KEY: ${SECRET_KEY}
      EMAIL_ADDRESS: ${EMAIL_ADDRESS}
      EMAIL_HOST_PASSWORD: ${EMAIL_HOST_PASSWORD}
    volumes:
      - .:/app
    # depends_on:
    #   - db
    #   - redis
#   db:
#     image: postgres:15
#     environment:
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: example
#       POSTGRES_DB: mydatabase
#     volumes:
#       - db_data:/var/lib/postgresql/data

#   redis:
#     image: redis:7
#     command: redis-server

# volumes:
#   static_volume:
#   media_volume:
#   db_data:
